### ISSUE TITLE
from binance.enums import HistoricalKlinesType

### ISSUE THREAD

**Issue by tyomastag** [cakel/binance_bband_telegram#1]
not works HostoricalKlinesType in binance.enums

**Comment by cakel** [comment]
Would you tell me in detail how it doesn't work ?
Do you mean `from binance.enums import HistoricalKlinesType` doesn't work ?

If it's code issue itself, I can tell why as far as I know. Also visiting https://python-binance.readthedocs.io/en/latest/ will be helpful.
But if it's logical or algorithm issue. Please visit https://blog.finxter.com/bollinger-bands-algorithm-python-binance-api-for-crypto-trading/ and contact the author about your problem.

**Comment by azoo201110** [comment]
http://prntscr.com/64KJ8jEHxgML

C:\Users\azoo2\OneDrive\سطح المكتب\binance_bband_telegram>main.py
2022-03-19 06:59:25,357 |  INFO | <module>() main.py:70 | === Program Loop Start ===
Traceback (most recent call last):
  File "C:\Users\azoo2\OneDrive\سطح المكتب\binance_bband_telegram\main.py", line 71, in <module>
    initialize_listening()
  File "C:\Users\azoo2\OneDrive\سطح المكتب\binance_bband_telegram\_message.py", line 18, in initialize_listening
    bot.sendMessage(chat_id, f"봇이 (재)시작합니다.(v1.2)(비교가격:{config['BINANCE_TRACE_SYMBOL']}/비교간격:{config['BINANCE_TRACE_INTERVAL']})")
  File "C:\Users\azoo2\AppData\Local\Programs\Python\Python310\lib\site-packages\telepot\__init__.py", line 513, in sendMessage
    return self._api_request('sendMessage', _rectify(p))
  File "C:\Users\azoo2\AppData\Local\Programs\Python\Python310\lib\site-packages\telepot\__init__.py", line 491, in _api_request
    return api.request((self._token, method, params, files), **kwargs)
  File "C:\Users\azoo2\AppData\Local\Programs\Python\Python310\lib\site-packages\telepot\api.py", line 155, in request
    return _parse(r)
  File "C:\Users\azoo2\AppData\Local\Programs\Python\Python310\lib\site-packages\telepot\api.py", line 150, in _parse
    raise exception.TelegramError(description, error_code, data)
telepot.exception.TelegramError: ('Bad Request: chat not found', 400, {'ok': False, 'error_code': 400, 'description': 'Bad Request: chat not found'})

C:\Users\azoo2\OneDrive\سطح المكتب\binance_bband_telegram>

**Comment by azoo201110** [comment]
C:\Users\azoo2\OneDrive\سطح المكتب\binance_bband_telegram>main.py
2022-03-19 07:04:23,606 |  INFO | <module>() main.py:70 | === Program Loop Start ===
Traceback (most recent call last):
  File "C:\Users\azoo2\OneDrive\سطح المكتب\binance_bband_telegram\main.py", line 71, in <module>
    initialize_listening()
  File "C:\Users\azoo2\OneDrive\سطح المكتب\binance_bband_telegram\_message.py", line 18, in initialize_listening
    bot.sendMessage(chat_id, f"봇이 (재)시작합니다.(v1.2)(비교가격:{config['BINANCE_TRACE_SYMBOL']}/비교간격:{config['BINANCE_TRACE_INTERVAL']})")
  File "C:\Users\azoo2\AppData\Local\Programs\Python\Python310\lib\site-packages\telepot\__init__.py", line 513, in sendMessage
    return self._api_request('sendMessage', _rectify(p))
  File "C:\Users\azoo2\AppData\Local\Programs\Python\Python310\lib\site-packages\telepot\__init__.py", line 491, in _api_request
    return api.request((self._token, method, params, files), **kwargs)
  File "C:\Users\azoo2\AppData\Local\Programs\Python\Python310\lib\site-packages\telepot\api.py", line 155, in request
    return _parse(r)
  File "C:\Users\azoo2\AppData\Local\Programs\Python\Python310\lib\site-packages\telepot\api.py", line 150, in _parse
    raise exception.TelegramError(description, error_code, data)
telepot.exception.TelegramError: ('Bad Request: chat not found', 400, {'ok': False, 'error_code': 400, 'description': 'Bad Request: chat not found'})

C:\Users\azoo2\OneDrive\سطح المكتب\binance_bband_telegram>

**Comment by cakel** [comment]
@azoo201110 To make it work, you've got to make a Telegram preparation following,
1) Create a Telegram Bot using Bot Father.
Make a one using https://telegram.me/BotFather

2) Talk with bot with your telegram client and get Chat ID by visiting
https://api.telegram.org/bot[Bot ID]/getUpdates
BotID is your created Bot ID, which botfather offered
it shows detail information with **Chat ID**

You should modify **.env** file as retrieved **Bot ID** and **Chat ID**
For more detail, visit https://sean-bradley.medium.com/get-telegram-chat-id-80b575520659

**Comment by azoo201110** [comment]
2022-03-22 01:14:56,135 |  INFO | <module>() main.py:70 | === Program Loop Start ===
Traceback (most recent call last):
  File "C:\Users\azoo2\OneDrive\سطح المكتب\binance_bband_telegram\main.py", line 72, in <module>
    mainloop()
  File "C:\Users\azoo2\OneDrive\سطح المكتب\binance_bband_telegram\main.py", line 20, in mainloop
    now_time = now.strftime('%Y년%m월%d일 %H시%M분%S초')
UnicodeEncodeError: 'locale' codec can't encode character '\ub144' in position 2: encoding error

**Comment by cakel** [comment]
@azoo201110  In that case, 2 things checks to resolve

1. Check installed Python's major version is 3, instead of 2.
`C:\Users\cakel>python --version`
`Python 3.9.7`
Above example, Python major version is 3

2. Try change Korean characters to English characters, for example
Before
`now_time = now.strftime('%Y년%m월%d일 %H시%M분%S초')`
After 
`now_time = now.strftime('%Y/%m/%d/ %H:%M:%S')`

**Comment by azoo201110** [comment]
Traceback (most recent call last):
  File "C:\Users\azoo2\OneDrive\سطح المكتب\binance_bband_telegram\main.py", line 2, in <module>
    from _message import initialize_listening
  File "C:\Users\azoo2\OneDrive\سطح المكتب\binance_bband_telegram\_message.py", line 1, in <module>
    ﻿import telepot
ModuleNotFoundError: No module named 'telepot'

**Comment by cakel** [comment]
@azoo201110
It said telepot wasn't installed properly. To clear simply, run `setup.bat` and run `python main.py` again.
`setup.bat` makes a virtual environment that resolves dependency issues including telepot, temporally and automatically.
Or If you want to resolve permanently, you can use `pip --user -r requirements.txt`

**Comment by cakel** [comment]
I'd like to close this issue, since it's not updated for a long time.
